# Generated by Django 5.0.6 on 2024-06-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
