# Generated by Django 5.0.6 on 2024-06-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='body',
            new_name='message',
        ),
    ]
